[project]
name = "pchem_labbook"
readme = "README.md"
version = "0.1"
requires-python = ">=3.8"
dependencies = [
    "sphinx",
    "sphinx-book-theme",
    "sphinx_design",
    "matplotlib",
    "scipy"
]

[tool.setuptools.packages.find]
include = ["source"]