# https://taskfile.dev/
version: '3'

vars:
  PROJECT_NAME: pchem_labbook
  SPHINX_BUILD: .venv/bin/sphinx-build  # run from within virtualenv
  SPHINX_OPTS: ""
  SPHINX_SOURCE_DIR: source
  SPHINX_BUILD_DIR: build

tasks:

  create-env:
    desc: Create a local virtual environment for development
    internal: true
    cmds:
      - python3 -m venv .venv
    generates:
      - .venv

  install:
    desc: Install the package in development (edit) mode
    cmds:
      - python3 -m pip install -e "."
    sources:
      - pyproject.toml

  setup:
    desc: Setup the development environment
    cmds:
      - task: create-env
      - task: install

  build:
    desc: Build the documentation
    dir: .
    cmds:
      - "{{.SPHINX_BUILD}} -M html {{.SPHINX_SOURCE_DIR}} {{.SPHINX_BUILD_DIR}} -E -a -W {{.SPHINX_OPTS}}"
      #- "{{.SPHINX_BUILD}} -M latexpdf {{.SPHINX_SOURCE_DIR}} {{.SPHINX_BUILD_DIR}} -E -a -W {{.SPHINX_OPTS}}"
    sources:
      - "**/*.md"
      - "**/*.rst"
      - "_static/**"
      - "conf.py"
